name: flutter_application
description: "A new Flutter project."
publish_to: "none" 
version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  image_picker: ^1.0.7
  path: ^1.8.0
  auto_route: ^7.8.4
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  email_validator: "^2.1.17"
  dio: ^5.4.1
  file_picker: ^6.1.1
  logger: ^2.0.2+1
  indexed: ^0.0.8
  intl: ^0.19.0
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  flutter_launcher_icons: ^0.13.1
  firebase_messaging: ^14.7.15
  firebase_storage: ^11.1.0
  flutter_local_notifications: ^17.1.2
  get_it: 7.6.7
  lottie: ^3.1.2
  ntp: ^2.0.0
  pin_code_fields: ^8.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  auto_route_generator: ^7.3.2
  flutter_lints: ^2.0.0


flutter_icons:
  android: true
  ios: true
  image_path: "assets/img/AppIcon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/img/AppIcon.png"
flutter:

  uses-material-design: true

  assets:
    - assets/img/
    - assets/lottie/internet.json

